name: "RISKEN Security Review"
description: "Security Code Review by RISKEN"
inputs:
  github_event_path:
    description: "GitHub event path"
    required: true
    default: ""
  github_token:
    description: "GitHub token"
    required: true
    default: ""
  github_workspace:
    description: "GitHub workspace"
    required: true
    default: ""
  risken_console_url:
    description: "RISKEN Console URL"
    default: ""
  risken_api_endpoint:
    description: "RISKEN API endpoint"
    default: ""
  risken_api_token:
    description: "RISKEN API token"
    default: ""
  options:
    description: "Other options"
    default: ""
runs:
  using: "docker"
  image: "docker://ssgca/security-review:v1"
  args:
    - "--github-event-path"
    - ${{ inputs.github_event_path}}
    - "--github-token"
    - ${{ inputs.github_token}}
    - "--github-workspace"
    - ${{ inputs.github_workspace}}
    - "--risken-console-url"
    - ${{ inputs.risken_console_url}}
    - "--risken-api-endpoint"
    - ${{ inputs.risken_api_endpoint}}
    - "--risken-api-token"
    - ${{ inputs.risken_api_token}}
    - ${{ inputs.options}}
branding:
  icon: "check-circle"
  color: "white"
