name: "RISKEN Security Review"
description: "Security Code Review by RISKEN"
inputs:
  github_event_path:
    description: "GitHub event path"
    required: true
    default: ""
  github_token:
    description: "GitHub token"
    required: true
    default: ""
  github_workspace:
    description: "GitHub workspace"
    required: true
    default: ""
  risken_endpoint:
    description: "Endpoint of the RISKEN API"
    default: ""
  risken_api_token:
    description: "RISKEN API token"
    default: ""
runs:
  using: "docker"
  image: "ssgca/security-review:v1.0.3"
  args:
    - "--github-event-path"
    - ${{ inputs.github_event_path}}
    - "--github-token"
    - ${{ inputs.github_token}}
    - "--github-workspace"
    - ${{ inputs.github_workspace}}
    - "--risken-endpoint"
    - ${{ inputs.risken_endpoint}}
    - "--risken-api-token"
    - ${{ inputs.risken_api_token}}
branding:
  icon: "check-circle"
  color: "white"
