name: "RISKEN Security Review"
description: "Call an RISKEN API."
inputs:
  github_event_path:
    description: "GitHub event path"
    required: true
    default: ""
  github_token:
    description: "GitHub token"
    required: true
    default: ""
  source_code_path:
    description: "SourceCode path"
    required: true
    default: ""
  risken_endpoint:
    description: "Endpoint of the RISKEN API"
    default: ""
  risken_api_token:
    description: "RISKEN API token"
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--github-event-path"
    - ${{ inputs.github_event_path}}
    - "--github-token"
    - ${{ inputs.github_token}}
    - "--source-code-path"
    - ${{ inputs.source_code_path}}
    - "--risken-endpoint"
    - ${{ inputs.risken_endpoint}}
    - "--risken-api-token"
    - ${{ inputs.risken_api_token}}
