name: Lint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/**.go'
      - 'go.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install linter
      run: make install
    - name: Run linter
      run: make lint
