name: Lint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/**.go'
      - 'go.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v3
      with:
        go-version: 1.21
    - name: GolangCI-Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55.2
        args: --timeout 5m
    - name: Deadcode
      run: |
        go install golang.org/x/tools/cmd/deadcode@v0.17.0
        deadcode ./...
