name: Security Code Review on PR
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # risken review needs this permission to create a comment on the PR

    steps:
      - uses: actions/checkout@v4
      - uses: ca-risken/security-review@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          risken_console_url: $RISKEN_CONSOLE_URL # optional
          risken_api_endpoint: $RISKEN_API_ENDPOINT # optional
          risken_api_token: ${{ secrets.RISKEN_API_TOKEN }} # optional
